import { Inter } from "next/font/google";
import "./globals.css";


// import "react-toastify/dist/ReactToastify.css";


// import Footer from "@/components/Footer";
import AuthProvider from "../../services/AuthProvider";
import Navbar from "@/components/Homepage/Navbar";
// import { ToastContainer } from "react-toastify";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-white`}>
        {/* <ToastContainer /> */}
        {/* <AuthProvider> */}
          <Navbar />

          {children}

          {/* <Footer/> */}
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
